apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: webapp
  labels:
    app: employees
spec:
  selector:
    app: employees
  ports:
   - protocol: TCP
     port: 80
     targetPort: 8080
     nodePort: 30000
  type: NodePort