apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: sqldb
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: 341161928846.dkr.ecr.us-east-1.amazonaws.com/rselvaraj03:dbv1.0
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "pw"
  restartPolicy: Always
  imagePullSecrets:
    - name: aws-ecr-secret
