apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql
  namespace: sqldb
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 341161928846.dkr.ecr.us-east-1.amazonaws.com/rselvaraj03:dbv1.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "pw"
      restartPolicy: Always
