apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: webapp
  labels:
    app: employees
spec:
  containers:
    - name: myapp-container
      image: 341161928846.dkr.ecr.us-east-1.amazonaws.com/rselvaraj03:appv1.0
      ports:
        - containerPort: 80
      env:
        - name: DBPWD
          value: "pw"
        - name: DBPORT
          value: "3306"
        - name: DBHOST
          value: mysql.sqldb.svc.cluster.local
        - name: DBUSER
          value: "root"
        - name: DATABASE
          value: employees
        - name: APP_COLOR
          value: blue
  restartPolicy: Always
  imagePullSecrets:
    - name: aws-ecr-secret